set vb t_vb=       " disable audible bells
let s:font='Consolas\ NF:h9'
if has('nvim')
    if exists("g:neovide")
        set guifont=Consolas\ NF:h12
        let g:neovide_cursor_animation_length=0
        let g:neovide_scroll_animation_length=0
    else
        GuiTabline 0
        GuiScrollBar 1
        execute 'GuiFont! ' . s:font
    endif
else
    execute 'set guifont=' . s:font
	set lines=50
	set columns=120
    set guioptions-=T  " no toolbar
    set guioptions-=t  " no tearoff menu
    set guioptions-=m  " don't show GUI menu
    set guioptions+=c  " use console dialog for simple questions
endif
