# bash configuration

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

for file in ~/.bash/{prompt,aliases,functions}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

## completion ##
[ -f /etc/bash_completion ] && source /etc/bash_completion
for file in completions/*; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file"
done

# make git alias 'g' work with completion
complete -o bashdefault -o default -o nospace -F _git g 2>/dev/null \
	|| complete -o default -o nospace -F _git g

## local config ##
[ -f $HOME/.localrc ] && source $HOME/.localrc

## history ##
# Don't put duplicate lines in the history.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups

## python ##
export PYTHONSTARTUP="$HOME/.pythonrc.py"
