# base-files version 4.1-1

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

## functions ##
if [ -f "${HOME}/.bash_functions" ]; then
  source "${HOME}/.bash_functions"
fi

## aliases ##
if [ -f "${HOME}/.bash_aliases" ]; then
  source "${HOME}/.bash_aliases"
fi

alias cd=cd_func

## completion ##
if [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

## prompt ##
source $HOME/.bash_prompt

## history ##
# Don't put duplicate lines in the history.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups

## python ##
export PYTHONSTARTUP="$HOME/.pythonrc.py"
